name: Docs

# why isn't this just on: push: ?
# because we want to test different build patterns, that's why
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.stoat/**'
      - '.github/workflows/docs.yaml'
  pull_request:
    paths:
      - 'docs/**'
      - '.stoat/**'
      - '.github/workflows/docs.yaml'

defaults:
  run:
    working-directory: docs

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 18

      - name: Setup cache
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          path: |
            ${{ github.workspace }}/docs/node_modules
          key: ${{ runner.os }}-node-16-${{ hashFiles('docs/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Download baseline logo image
        run: curl https://stoat-dev--static.stoat.page/branding/128.png -o build/baseline-logo-128.png

      - name: Run stoat action
        uses: ./
        if: always()
