name: Test CLI
on:
  pull_request:
    branches:
      - main
    paths:
      - 'cli/**'
      - '.stoat/**'
      - '.github/workflows/test-cli.yaml'
  push:
    branches:
      - main
    paths:
      - 'cli/**'
      - '.stoat/**'
      - '.github/workflows/test-cli.yaml'

defaults:
  run:
    working-directory: cli

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
      - name: Setup cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ${{ github.workspace }}/types/node_modules
            ${{ github.workspace }}/action/node_modules
            ${{ github.workspace }}/cli/node_modules
          key: ${{ runner.os }}-node-20-cli-${{ hashFiles('types/yarn.lock') }}-${{ hashFiles('action/yarn.lock') }}-${{ hashFiles('cli/yarn.lock') }}
      - name: Install types dependencies
        working-directory: types
        run: |
          yarn install --frozen-lockfile
      - name: Install action dependencies
        working-directory: action
        run: |
          yarn install --frozen-lockfile
      - name: Install cli dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Build and test stoat cli
        run: |
          yarn build
          yarn test
      - name: Check format
        run: yarn format-check
      - name: Run stoat action
        uses: ./
        if: always()
